## Perform KNN algorithm

In [60]:
import pandas as pd
import math

In [61]:
# Label the class of each genre, pop = 0, rnb = 1
labelled_pop = pd.read_excel("filepop.xlsx", index_col=0, usecols=[0,1,2,3,4,5,6,7,8,9,10,11])
labelled_rnb = pd.read_excel("filernb.xlsx", index_col=0, usecols=[0,1,2,3,4,5,6,7,8,9,10,11])
labelled_pop["Class"] = 0
labelled_rnb["Class"] = 1

# Combine to create a full dataframe
full_data = labelled_pop.append(labelled_rnb[:200], ignore_index=True) #1861

# Scale between 0 and 1
full_data["Key"] = (full_data["Key"] / full_data["Key"].max())
full_data["Tempo"] = (full_data["Tempo"] / full_data["Tempo"].max())
full_data["Loudness"] = (full_data["Loudness"] / full_data["Loudness"].min())

full_data_random = full_data.sample(frac=1)
full_data_random

Danceability  Mode  Energy       Key  Loudness  Speechiness  Acousticness  \
62         0.711     0   0.640  0.545455  0.559082       0.1730        0.1330   
30         0.556     0   0.661  0.545455  0.427628       0.2040        0.3000   
23         0.614     0   0.644  0.181818  0.454715       0.0426        0.0134   
3          0.604     1   0.741  0.181818  0.471559       0.0475        0.1780   
20         0.695     1   0.540  0.363636  0.481801       0.0493        0.2990   
..           ...   ...     ...       ...       ...          ...           ...   
32         0.773     0   0.742  0.454545  0.311326       0.0460        0.0206   
67         0.626     0   0.463  0.636364  0.639834       0.1220        0.6200   
48         0.831     0   0.554  0.090909  0.846284       0.2180        0.1610   
69         0.570     1   0.573  0.454545  0.587015       0.4760        0.1560   
47         0.783     1   0.750  0.454545  0.487726       0.0780        0.4260   

    Instrumentalness  Liveness  Valence     Tempo  Class  
62          0.000000    0.1250   0.5790  0.743640      1  
30          0.000000    0.1010   0.6680  0.907569      0  
23          0.000007    0.1170   0.6510  0.861673      0  
3           0.000035    0.4090   0.4730  0.828889      0  
20          0.000000    0.3670   0.4150  0.656512      0  
..               ...       ...      ...       ...    ...  
32          0.000000    0.0754   0.5710  0.614186      0  
67          0.000007    0.1770   0.0743  0.780640      1  
48          0.000061    0.1520   0.3960  0.753935      0  
69          0.000000    0.2560   0.5170  0.409235      1  
47          0.000000    0.2410   0.8800  0.527403      0  

[100 rows x 12 columns]

### Training data

In [62]:
# Get x training data
x_train = full_data_random[0:100]

# Target values
y_train = x_train["Class"].values

# Remove target values from x_data
x_train = x_train.drop("Class", axis=1)
x_train

Danceability  Mode  Energy       Key  Loudness  Speechiness  Acousticness  \
62         0.711     0   0.640  0.545455  0.559082       0.1730        0.1330   
30         0.556     0   0.661  0.545455  0.427628       0.2040        0.3000   
23         0.614     0   0.644  0.181818  0.454715       0.0426        0.0134   
3          0.604     1   0.741  0.181818  0.471559       0.0475        0.1780   
20         0.695     1   0.540  0.363636  0.481801       0.0493        0.2990   
..           ...   ...     ...       ...       ...          ...           ...   
32         0.773     0   0.742  0.454545  0.311326       0.0460        0.0206   
67         0.626     0   0.463  0.636364  0.639834       0.1220        0.6200   
48         0.831     0   0.554  0.090909  0.846284       0.2180        0.1610   
69         0.570     1   0.573  0.454545  0.587015       0.4760        0.1560   
47         0.783     1   0.750  0.454545  0.487726       0.0780        0.4260   

    Instrumentalness  Liveness  Valence     Tempo  
62          0.000000    0.1250   0.5790  0.743640  
30          0.000000    0.1010   0.6680  0.907569  
23          0.000007    0.1170   0.6510  0.861673  
3           0.000035    0.4090   0.4730  0.828889  
20          0.000000    0.3670   0.4150  0.656512  
..               ...       ...      ...       ...  
32          0.000000    0.0754   0.5710  0.614186  
67          0.000007    0.1770   0.0743  0.780640  
48          0.000061    0.1520   0.3960  0.753935  
69          0.000000    0.2560   0.5170  0.409235  
47          0.000000    0.2410   0.8800  0.527403  

[100 rows x 11 columns]

### Fit the KNN model

In [63]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

knn = KNeighborsClassifier(n_neighbors=1)

#cross_validate
cv_scores = cross_val_score(knn, x_train, y_train, cv=10)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [64]:
cv_scores_mean = np.mean(cv_scores)
print(cv_scores , "\n\n""mean =" ,"{:.2f}".format(cv_scores_mean))

[0.6 0.5 0.6 0.7 0.5 0.6 0.6 0.7 0.5 0.6] 

mean = 0.59


### Test Data

In [65]:
x_test = full_data_random[70:]

# Randomise the data
x_test = x_test.sample(frac=1)

y_test = x_test["Class"].values

x_test = x_test.drop("Class", axis=1)
x_test

Danceability  Mode  Energy       Key  Loudness  Speechiness  Acousticness  \
47         0.783     1   0.750  0.454545  0.487726       0.0780      0.426000   
5          0.761     1   0.525  1.000000  0.584053       0.0944      0.440000   
54         0.647     0   0.581  0.363636  0.649907       0.0884      0.002900   
84         0.895     0   0.468  0.000000  0.488996       0.3780      0.342000   
80         0.615     1   0.600  0.909091  0.475707       0.2700      0.107000   
25         0.684     1   0.545  0.090909  0.582783       0.1210      0.159000   
86         0.883     1   0.606  0.090909  0.374217       0.2380      0.267000   
69         0.570     1   0.573  0.454545  0.587015       0.4760      0.156000   
21         0.814     1   0.628  0.636364  0.607584       0.2210      0.167000   
2          0.905     1   0.563  0.727273  0.519299       0.1020      0.025400   
27         0.583     1   0.834  0.000000  0.412646       0.0444      0.049500   
56         0.684     1   0.545  0.090909  0.582783       0.1210      0.159000   
53         0.643     0   0.605  0.363636  0.505163       0.2970      0.033600   
38         0.745     1   0.650  0.181818  1.000000       0.3460      0.045100   
44         0.954     0   0.367  0.363636  0.808448       0.2880      0.341000   
67         0.626     0   0.463  0.636364  0.639834       0.1220      0.620000   
34         0.664     1   0.609  0.090909  0.550956       0.0707      0.304000   
13         0.796     1   0.798  0.090909  0.534281       0.0317      0.034000   
77         0.722     1   0.675  0.090909  0.621635       0.4080      0.419000   
48         0.831     0   0.554  0.090909  0.846284       0.2180      0.161000   
35         0.334     1   0.599  0.000000  0.486034       0.0365      0.046800   
29         0.808     0   0.897  1.000000  0.314203       0.0348      0.046900   
32         0.773     0   0.742  0.454545  0.311326       0.0460      0.020600   
4          0.737     0   0.846  0.090909  0.381750       0.2200      0.006140   
76         0.644     0   0.671  1.000000  0.436431       0.3150      0.022500   
68         0.676     1   0.610  0.090909  0.777467       0.2730      0.000114   
93         0.732     1   0.734  1.000000  0.674454       0.0974      0.136000   
97         0.660     1   0.831  0.545455  0.453360       0.0460      0.174000   
92         0.474     0   0.801  0.727273  0.506010       0.3750      0.102000   
88         0.707     1   0.909  0.181818  0.296343       0.2610      0.413000   

    Instrumentalness  Liveness  Valence     Tempo  
47          0.000000    0.2410   0.8800  0.527403  
5           0.000007    0.0921   0.5310  0.435424  
54          0.000008    0.1190   0.1130  0.808439  
84          0.000000    0.2130   0.4280  0.635443  
80          0.000002    0.2830   0.0661  0.700097  
25          0.000000    0.1020   0.4070  0.770211  
86          0.000000    0.0952   0.4950  0.645862  
69          0.000000    0.2560   0.5170  0.409235  
21          0.000000    0.1010   0.6770  0.667523  
2           0.000010    0.1130   0.3240  0.576104  
27          0.000000    0.0658   0.5570  0.936509  
56          0.000000    0.1020   0.4070  0.770211  
53          0.000000    0.1120   0.1450  0.453440  
38          0.007580    0.1110   0.3860  0.775585  
44          0.000005    0.0979   0.3720  0.667787  
67          0.000007    0.1770   0.0743  0.780640  
34          0.000000    0.0926   0.1940  0.700173  
13          0.000042    0.0952   0.9420  0.624745  
77          0.000000    0.1060   0.7780  0.753116  
48          0.000061    0.1520   0.3960  0.753935  
35          0.000392    0.2050   0.1270  0.870848  
29          0.000031    0.3640   0.5910  0.678555  
32          0.000000    0.0754   0.5710  0.614186  
4           0.000000    0.0486   0.5460  0.473711  
76          0.000000    0.0855   0.5630  0.710726  
68          0.000002    0.1910   0.5190  0.839969  
93          0.000901    0.1650   0.4880  0.784603  
97          0.000001    0.1630   0.6

In [66]:
predictions = knn.predict(x_test)
predictions

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [67]:
accuracy_score = knn.score(x_test, y_test)
print("Accuracy score = ""{:.2f}".format(accuracy_score))

Accuracy score = 0.90


In [68]:
from sklearn.metrics import confusion_matrix

confusion_matrix = confusion_matrix(y_test, predictions)
confusion_matrix

array([[14,  1],
       [ 2, 13]], dtype=int64)